config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get '/' => "welcome#index"

  get '/about' => "welcome#about", as: :about
  get '/services' => "welcome#services", as: :services
  get '/contact' => 'contact#contact', as: :contact
  post '/contact' => 'contact#create', as: :create







  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :products do
    resources :reviews, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]


  end


  resources :reviews, only: [] do

    resources :likes, only: [:create, :destroy]
  end
  # resources :products
  # get '/products/new' => 'products#new', as: :new_products
  # post '/products' => 'products#create', as: :products
  # get '/products/:id' => 'products#show', as: :product
  # get '/products' => 'products#index'
  # get '/products/:id' => 'products#edit', as: :edit_products
  # patch '/products/:id' => 'products#update'
  # delete '/products/:id' => 'products#destroy'

  get '/users/new' => "users#new", as: :new_users


root 'home#index'
end
# get '/questions/new' => "questions#new", as: :new_question
# post '/questions' => "questions#create", as: :questions
# get "/questions/:id" => "questions#show",   as: :question
# get'/questions' => 'questions#index'
# get '/questions/:id/edit' => "questions#edit", as: :edit_question
# patch '/questions/:id' => "questions#update"
# delete '/questions/:id' => 'questions#destroy'

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review
  validates :user_id, uniqueness: {scope: :review_id,
                                            message: "liked it already"}
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :authenticate_use!

  def create
    @review = Review.find params[:review_id]
    @like = Like.new user: current_user, review: @review

    respond_to do |format|
      if !(can? :like, @review)
        # redirect_to root_path, alert: "access denied"
      format.html { redirect_to root_path, alert: "access denied"}
      format.js { render :access_denied}


      elsif @like.save
        format.html {redirect_to product_path(@review.product_id), notice: "thank you "}
        format.js { render :create_success}

      else
        format.html {redirect_to product_path(@review.product_id), alert: like.errors.full.messages.join(", ")}
        format.js { render :create_failure}
      end
    end
  end


  def destroy
    @review = Review.find params[:review_id]
    @like = Like.find params[:id]
    respond_to do |format|
    if can? :destroy, @like
      @like.destroy
    format.html {  redirect_to product_path(@review.product_id), notice: "Unliked"}
    format.js { render}
    end
  end
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_like.present? %>
  <!-- like bottom for review -->
  <%= link_to image_tag("http://icons.iconarchive.com/icons/iconsmind/outline/48/Unlike-2-icon.png", border: 0), review_like_path(review, user_like), method: :delete, remote: true %>
<% else %>
  <!-- Delete bottom for review -->
  <%= link_to image_tag("http://icons.iconarchive.com/icons/iconsmind/outline/48/Like-2-icon.png", border: 0), review_likes_path(review), method: :post, remote: true, class: "like" %>
<% end %>

app/views/likes/create_success.js.erb
$('#<%= dom_id(@review) %> .like').html('').prepend('<%= j(render('/likes/like', {review: @review, user_like: @like})) %>');

app/views/likes/destroy.html.erb
$('#<%= dom_id(@review) %> .like').html('').prepend('<%= j(render('/likes/like', {review: @review, user_like: nil})) %>');