config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get '/' => "welcome#index"

  get '/about' => "welcome#about", as: :about
  get '/services' => "welcome#services", as: :services
  get '/contact' => 'contact#contact', as: :contact
  post '/contact' => 'contact#create', as: :create







  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :products do
    resources :reviews, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]


  end


  resources :reviews, only: [] do

    resources :likes, only: [:create, :destroy]
  end
  # resources :products
  # get '/products/new' => 'products#new', as: :new_products
  # post '/products' => 'products#create', as: :products
  # get '/products/:id' => 'products#show', as: :product
  # get '/products' => 'products#index'
  # get '/products/:id' => 'products#edit', as: :edit_products
  # patch '/products/:id' => 'products#update'
  # delete '/products/:id' => 'products#destroy'

  get '/users/new' => "users#new", as: :new_users


root 'home#index'
end
# get '/questions/new' => "questions#new", as: :new_question
# post '/questions' => "questions#create", as: :questions
# get "/questions/:id" => "questions#show",   as: :question
# get'/questions' => 'questions#index'
# get '/questions/:id/edit' => "questions#edit", as: :edit_question
# patch '/questions/:id' => "questions#update"
# delete '/questions/:id' => 'questions#destroy'

app/models/product.rb
class Product < ApplicationRecord
has_many :reviews, dependent: :destroy
belongs_to :category
belongs_to :user


    has_many :favourites, dependent: :destroy
    has_many :users, through: :favourites 


  # validates :title, presence: true, uniqueness: true
  validates :price, presence: true
  # validates :title, uniqueness: true
  validates :price,  inclusion: 0..2500
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 0}
  # validates :title, case_sensitive: false
  validates :description, presence: true, length: {minimum: 10}
  #
  # after_initialize :set_defaults
  # # before_save :capitalize_title
  after_save :titleized_title

# deligate line for making relationship beetween two diffrent table
  # delegate :name, to: :category, prefix: true

  def self.search(keyword)
    where(["title ILIKE ? or description ILIKE ?", "%#{keyword}%", "%#{keyword}%"])


  end

  def next
      Product.order(:id).limit(10).offset((@page - 1) * 10)
    end

    def previous
      Product.order(:id).limit(10).offset((@page + 1) * 10)
    end

    def favourite_for(user)
      favourites.find_by_user_id user
    end

  private

  def set_defaults
    self.price ||= 1
  end

  def titleized_title

    self.title.capitalize! if title

  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # load_and_authorize_resource

    before_action :find_product, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_use!, only: [:create, :edit, :destroy, :update, :new]
    before_action :authorize, only: [:destroy, :update, :edit]

  def new
    @product = Product.new
    @category = Category.all
  end

  def index

      @products = Product.order(created_at: :desc ).page(params[:page]).per_page(10)
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def edit
    @product = Product.find params[:id]

    # authorize! :edit, @product

  end
  def update
      @product = Product.find params[:id]
    if @product.update params.require(:product).permit([:title, :description, :price, :category_id])
      redirect_to products_path
    else
      render :edit
    end
  end

  def create
    # we are using strong parameters feature of rails here to only allow
    # mass_assigning the attributes that we want to allow the user to set
    product_params = params.require(:product).permit([:title, :description, :price, :category_id])
    @product = Product.new product_params
    @product.user = current_user
    if @product.save
      # render json: params
      # redirect_to question_path({id: @question.id})
      # redirect_to question_path({id: @question})
      # redirect_to question_path(@question)
       redirect_to product_path(@product), notice: " Product created successfully"

    else
      render :new
    end
  end


  def show
      @product = Product.find params[:id]
      @category = @product.category
      @review = Review.new
      @like = Like.all
  end

  private

  def find_product
    @product = Product.find params[:id]
  end

  def authorize
    redirect_to root_path, alert: "access defined" unless can? :manage, @product
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1> Update product</h1>
<%= @product.errors.full_messages.join(", ") %>
<%= form_for @product do |f| %>
<div class="form-group row">
<%= f.label(:title, class: "col-xs-2 col-form-label") %>
<div class=" col-xs-10">
<%= f.text_field :title %>
</div>
</div>
<div class="form-group row">
 <%= f.label(:description, class: "col-xs-2 col-form-label") %>
 <div class=" col-xs-10">
 <%= f.text_area :description %>
 </div>
</div>
<div class="form-group row">
 <%= f.label(:price, class: "col-xs-2 col-form-label") %>
 <div class=" col-xs-10">
 <%= f.text_field :price %>
 </div>
</div>


<%= f.submit ("Update Now"), {class: "btn btn-info btn-lg"} %>

<% end %>

app/views/products/index.html.erb
<div class="container">
<h1>list of my products</h1>

<div>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>photo</th>
  </tr>
  </thead>

<tbody>

      <% @products.each do |prod| %>
    <td class="col-md-4"><%= link_to prod.title, product_path(prod) %></td>
    <td class="col-md-4"><%= prod.description %></td>
    <td class="col-md-4"><%= prod.price %></td>
    <% if can? :manage, prod %>
    <td class="col-md-4"><%= link_to "Edit", edit_product_path(prod.id),{class: "btn btn-info btn-lg"} %></td>
    <td class="col-md-4"><%= link_to "Delete", product_path(prod.id), class: "btn btn-info btn-lg", method: :delete, data: {confirm: "Are you sure?"} %></td>
    <% end %> 
    <td><img src="<%= prod.photo %>"></td>

  </tr>
<% end %>
</tbody>
</table>
<div class="digg_pagination">
<%= will_paginate @products, previous_label: h("<"), next_label: h(">") %>
</div>

</div>
</br>
<hr>
<div>
  <div class="row">
    <% @products.each do |prod| %>
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <img src="<%= prod.photo%>" alt="...">
    </a>
    <span style="color: blue"><h4><%= prod.title.first(25) %></h4>, <b>Price is <%= prod.price %></b></span><br>
    <span><%= prod.description.first(75) %></span>
  </div>


    <% end %>
</div>
</div>
</div>

app/views/products/new.html.erb
<div class="container">
<%= @product.errors.full_messages.join(",") %>
<%= form_for @product do |f| %>
<div class="form-group row">
<%= f.label(:title, class: "col-xs-2 col-form-label") %>
<div class=" col-xs-10">
<%= f.text_field :title %>
</div>
</div>
<div>
<div class="form-group row">
 <%= f.label(:description, class: "col-xs-2 col-form-label") %>
 <div class=" col-xs-10">
 <%= f.text_area :description %>
 </div>
</div>
<div class="form-group row">
 <%= f.label(:price, class: "col-xs-2 col-form-label") %>
 <div class=" col-xs-10">
 <%= f.text_field :price %>
 </div>


<div class="field">
   <%= f.label :category %><br>
   <%= f.collection_select :category_id, Category.all, :id, :name %>
 </div>


</div>


<%= f.submit ("submit"), {class: "btn btn-info btn-lg"} %>

<% end %>
</div>

app/views/products/show.html.erb
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Tite
            </th>
            <th>Description</th>
            <th>Price</th>
            <th>Photo</th>
            <th>Category</th>

        </tr >
    </thead>

    <tbody>
        <tr>
            <td><%= @product.title %></td>
            <td><%= @product.description %></td>
            <td><%= @product.price %></td>
            <td><%= @product.photo %></td>
            <!-- abow line take the name of category from deligation from product model -->
            <!-- <td> <%# @product.category_name %></td> -->
            <!-- abow line take the name normal think -->
            <td>
                <%= @category.name %></td>
            <% if can? :manage, @product %>
            <td>
                <%= link_to "Edit", edit_product_path(@product.id),{class: "btn btn-info btn-md"} %>
            </td>
            <% end %>
            <% if can? :favourite, @product %>
            <% user_favourite = @product.favourite_for current_user %>
            <% if user_favourite.present? %>
            <td>
              <%= link_to image_tag("http://icons.iconarchive.com/icons/iconsmind/outline/48/Unlike-2-icon.png", border: 0), product_favourite_path(@product, user_favourite), method: :delete %>
              <% else %>
              <td>
              <%= link_to image_tag("http://icons.iconarchive.com/icons/iconsmind/outline/48/Like-2-icon.png", border: 0), product_favourites_path(@product), method: :post, class: "like" %>
              <% end %>
              <% else %>
              like
              <% end %>
              <div>
              (<%= pluralize @product.favourites.count, "Fav" %>)
              </div>
            </td>
        </tr>
    </tbody>
</table>
<%= form_for [@product, @review], remote: true do |f| %>
<div>
    <%= f.label :body %>
    <%= f.text_area :body %>
</div>
<div>
    <%= f.radio_button(:rating, 1) %>
    <%= f.radio_button(:rating, 2) %>
    <%= f.radio_button(:rating, 3) %>
    <%= f.radio_button(:rating, 4) %>
    <%= f.radio_button(:rating, 5) %>
</div>
<div>
    <%= f.submit %>
</div>
<% end %>
REVIEW

<div id="reviews">
<% @product.reviews.each do |rev| %>
<%= render "/reviews/review", review: rev %>
    <% end %>
</div>