config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get '/' => "welcome#index"

  get '/about' => "welcome#about", as: :about
  get '/services' => "welcome#services", as: :services
  get '/contact' => 'contact#contact', as: :contact
  post '/contact' => 'contact#create', as: :create







  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :products do
    resources :reviews, only: [:create, :destroy]
    resources :favourites, only: [:create, :destroy]


  end


  resources :reviews, only: [] do

    resources :likes, only: [:create, :destroy]
  end
  # resources :products
  # get '/products/new' => 'products#new', as: :new_products
  # post '/products' => 'products#create', as: :products
  # get '/products/:id' => 'products#show', as: :product
  # get '/products' => 'products#index'
  # get '/products/:id' => 'products#edit', as: :edit_products
  # patch '/products/:id' => 'products#update'
  # delete '/products/:id' => 'products#destroy'

  get '/users/new' => "users#new", as: :new_users


root 'home#index'
end
# get '/questions/new' => "questions#new", as: :new_question
# post '/questions' => "questions#create", as: :questions
# get "/questions/:id" => "questions#show",   as: :question
# get'/questions' => 'questions#index'
# get '/questions/:id/edit' => "questions#edit", as: :edit_question
# patch '/questions/:id' => "questions#update"
# delete '/questions/:id' => 'questions#destroy'

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @review = Review.new find_params
        @product = Product.find params[:product_id]
        @review.product = @product
        @category = Category.all
        respond_to do |format|
            if @review.save
                flash[:notice] = 'successfully Added'
                format.html { redirect_to product_path(@product)}
                format.js { render :create_success}
            else
                flash[:notice] = 'Fixed the errors'
                format.html {render '/products/show'}
                format.js { render :create_failure }
            end
        end
    end

    def destroy
        a = Product.find params[:product_id]
        # r = Review.find params[:id]
        @review = Review.find params[:id]
        respond_to do |format|
        @review.destroy
        format.html {redirect_to product_path(a), notice: 'review deleted!'}
        format.js {render}
        end
      end

    private

    def find_params
        params.require(:review).permit(:body, :rating)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<div id="<%= dom_id(review) %>">
    <%= review.body %>
    <%= "rating: #{review.rating} Star\s" %>

    <%# if can? :destroy, review %>

    <!-- delete bottom for delete review -->
    <%= link_to "delete", product_review_path(@product, review), method: :delete, remote: true, data: {confirm: "are you sure?"} %>
    <%# end %>

    <% if can? :like, review %>

        <% user_like = review.like_for current_user %>
        <%= render "/likes/like", {review: review, user_like: user_like} %>
        <!-- delete bottom for delete review -->
        </div>
        <% else %>
        like
        <% end %>
          (<%= pluralize review.likes.count, "Like" %>)

app/views/reviews/create_success.js.erb
$('#reviews').prepend('<%= j(render('/reviews/review', {review: @review})) %>');

app/views/reviews/destroy.html.erb
$('#<%= dom_id(user_like) %>').fadeOut(1000, function(){ $(this).remove(); });